// <auto-generated />
using System;
using FunctionExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunctionExplorer.Migrations
{
    [DbContext(typeof(AndmeKontekst))]
    partial class AndmeKontekstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FunctionExplorer.Models.FunktsiooniUurimine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ekstreemumid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KriitilisedPunktid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LuodudAeg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Maaramispiirkond")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nullkohad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tuletis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Valem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FunktsiooniUurimised");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ekstreemumid = "max: x = -1, y = 2; min: x = 1, y = -2",
                            KriitilisedPunktid = "x1 = -1; x2 = 1",
                            LuodudAeg = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Maaramispiirkond = "X: (-∞; ∞)",
                            Nullkohad = "x = -1.7321; 0; 1.7321",
                            Tuletis = "3*x^2 - 3",
                            Valem = "x^3 - 3*x"
                        },
                        new
                        {
                            Id = 2,
                            Ekstreemumid = "min: x = 2, y = -1",
                            KriitilisedPunktid = "x1 = 2",
                            LuodudAeg = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Maaramispiirkond = "X: (-∞; ∞)",
                            Nullkohad = "x = 1; 3",
                            Tuletis = "2*x - 4",
                            Valem = "x^2 - 4*x + 3"
                        },
                        new
                        {
                            Id = 3,
                            Ekstreemumid = "max: x = -2, y = 16; min: x = 2, y = -16",
                            KriitilisedPunktid = "x1 = -2; x2 = 2",
                            LuodudAeg = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Maaramispiirkond = "X: (-∞; ∞)",
                            Nullkohad = "x = -3.4641; 0; 3.4641",
                            Tuletis = "3*x^2 - 12",
                            Valem = "x^3 - 12*x"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
